package POJO;
// Generated 17-jul-2015 15:27:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Prueba generated by hbm2java
 */
public class Prueba  implements java.io.Serializable {


     private Integer id;
     private String session;
     private Date fecha;

    public Prueba() {
    }

    public Prueba(String session, Date fecha) {
       this.session = session;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


